"""
Python module for just text lines for test modules testing in certain areas, separated here for cleanliness
"""


LOREMIPSUM_PARAGRAPH = """Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum bibendum elit id est sodales, eu sollicitudin arcu condimentum. Fusce sodales lacus id leo venenatis, ut finibus velit facilisis. Morbi fringilla, massa eget dictum vulputate, odio lorem mollis ante, ac pretium tellus urna vitae dolor. Etiam porttitor ipsum at sapien lacinia hendrerit. Ut venenatis, eros vel ultricies ultrices, nisi libero viverra enim, gravida rhoncus velit nibh vel ex. Aenean quis odio non eros imperdiet consequat. Aliquam id aliquet libero. Cras eu ex ut lectus tempor facilisis. Pellentesque vel massa posuere, congue leo eu, dapibus orci. Suspendisse in arcu in quam fringilla tempus vel sed nisl.

Cras bibendum nunc metus, vel luctus nisl iaculis eu. Nulla eu fringilla neque. Donec pretium risus lacus, a eleifend leo consectetur id. Nam nec luctus turpis. Nam ultricies quam sed leo dapibus, et aliquet eros lobortis. Nullam metus lacus, posuere quis commodo nec, ultrices a eros. In vel elementum arcu, eu semper nisi. Aenean ac mollis diam. Donec elementum felis a pharetra vehicula. Phasellus sagittis ipsum sed felis accumsan molestie. Praesent urna nibh, maximus et finibus vitae, aliquet sit amet sapien. Nullam sit amet ex accumsan, lobortis arcu vel, finibus magna.

Praesent eget nunc sed sapien mattis ultrices. Aliquam lectus diam, varius quis aliquam eget, efficitur a dui. Nam ac hendrerit libero. Donec pellentesque velit nec lacinia porttitor. Morbi in risus id mi facilisis aliquam. Curabitur elementum nisl convallis, facilisis tortor eu, eleifend eros. Suspendisse cursus justo sed erat pretium consequat. Cras aliquam massa et laoreet scelerisque. Aenean volutpat lacus nec aliquam cursus. Cras pulvinar venenatis neque, sit amet blandit lorem elementum vitae.

Mauris sit amet bibendum enim. Suspendisse dignissim gravida lectus porta malesuada. Duis elementum, nulla id pretium placerat, nunc felis dapibus justo, vitae viverra mauris urna id tortor. Aliquam quis nisi eu velit cursus vestibulum non eu sem. Quisque nec sem auctor, porta justo nec, interdum ipsum. Mauris sollicitudin neque quam, ut pulvinar turpis porttitor a. Donec sit amet nisl id odio tincidunt varius ac a nibh.

Aenean ac tincidunt est. Mauris nunc orci, venenatis eget nibh quis, dictum cursus quam. In at eleifend metus. Maecenas sagittis quis dolor nec tempor. Sed ut nisl risus. Cras ligula nunc, tempor vitae pharetra non, sagittis varius arcu. Nunc semper lorem vitae purus ornare porta.

Maecenas cursus sem vulputate, aliquet nibh nec, pulvinar urna. Nunc at libero porttitor justo ultrices blandit. In pretium, enim quis ultricies cursus, dui ligula luctus dolor, ac elementum ipsum diam ac felis. Vivamus sit amet sem et mauris interdum blandit. Praesent eget tellus ipsum. Sed rhoncus rhoncus leo ut hendrerit. Nunc sed velit libero. Mauris turpis eros, placerat porttitor ligula ac, lacinia sollicitudin est. Quisque aliquet odio pharetra lacus tincidunt, quis tincidunt libero vulputate. Ut imperdiet, risus nec malesuada varius, sem erat semper eros, a maximus purus ex id nisi.

Etiam a nisi risus. Sed nisi justo, euismod quis vulputate sed, bibendum ut eros. Nulla neque ipsum, eleifend at lacus a, convallis molestie augue. Fusce sodales nisl at justo rhoncus, a feugiat nunc bibendum. Fusce eu metus id est fringilla condimentum a ac nibh. Etiam sit amet rutrum tellus, non blandit dolor. Suspendisse eu felis sed nunc egestas molestie. Integer cursus risus sed vulputate auctor. Suspendisse porttitor, ex vel pretium accumsan, magna diam feugiat mauris, ac vulputate lorem ligula at nisl. Aliquam ac venenatis magna. Nullam malesuada nisi et aliquet imperdiet. In interdum posuere massa in lobortis. Cras in eleifend lacus.

Nulla quis luctus tellus, et aliquam turpis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ut suscipit eros, ac ornare ipsum. Duis varius posuere lacus cursus porta. Sed pulvinar, lorem sit amet vulputate venenatis, est elit imperdiet urna, eget consectetur sem quam vel leo. Maecenas eleifend ultrices metus, vel lobortis orci tempor sit amet. Aliquam velit sapien, venenatis in ligula suscipit, mattis finibus est. Vivamus ultrices lorem tortor, ut semper eros feugiat quis. Donec sagittis massa est, eget aliquet tellus varius sit amet. Suspendisse potenti. Donec euismod tellus id vulputate imperdiet. Donec id velit non leo consequat sodales.

Donec ac vulputate magna. Sed eu lacinia dolor. Ut nibh turpis, accumsan vitae aliquam et, aliquam at ante. Curabitur eu ullamcorper enim. Vivamus in sodales justo, nec imperdiet nibh. In mauris lorem, tempor quis orci ultrices, tempor suscipit justo. Nullam lorem tellus, sodales id feugiat in, mattis hendrerit ante. Maecenas nec bibendum dui, a ultrices mauris. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras porttitor, turpis a rhoncus congue, tellus leo maximus sapien, eget fringilla leo nisi ut quam. Morbi quis ipsum ac erat tristique placerat. Cras commodo finibus lorem at porttitor.

Quisque felis elit, eleifend vitae vulputate in, eleifend nec lorem. Fusce varius quis lectus sed congue. Quisque sapien nunc, placerat nec efficitur ac, pharetra eu lorem. Phasellus mattis accumsan ligula nec tincidunt. Duis aliquam commodo quam pretium blandit. Etiam ac scelerisque sem, nec cursus nisl. Quisque dapibus sit amet augue sit amet bibendum. Duis gravida enim sit amet enim tristique varius. Aliquam at sagittis tortor. Quisque finibus augue quis purus rhoncus, a consequat lorem faucibus. Etiam et accumsan diam. Suspendisse venenatis, massa eget fermentum facilisis, urna neque consequat tellus, in egestas est ipsum vitae odio. Nulla pharetra maximus hendrerit. Cras sem odio, scelerisque vitae congue sed, lobortis ut dui. Curabitur nec eleifend sapien.

Pellentesque egestas lacus at ipsum convallis eleifend. Proin sit amet nibh eget orci suscipit tincidunt. Quisque nec sapien finibus lectus euismod gravida hendrerit eu enim. Ut et aliquet diam. Nulla luctus, ligula ac dictum mollis, nibh est placerat velit, ac malesuada lectus sem vel nulla. Curabitur sagittis dui in nibh euismod ultricies. Maecenas ac ullamcorper ligula, id pulvinar lectus. Nullam fermentum nisl et lectus congue elementum. Integer sit amet volutpat tortor. Vestibulum eget massa nibh. Nulla sed ornare velit. Phasellus luctus porta maximus. Integer eu fringilla justo, eget varius mi. Proin tempus metus id libero mattis facilisis.

Sed posuere elit velit, at congue ipsum maximus et. Vivamus ultricies nisl ipsum, vehicula scelerisque turpis ornare id. Aenean sapien orci, accumsan sed risus sodales, tincidunt interdum erat. Sed non viverra dolor, at gravida nisl. Curabitur consectetur odio sed sapien venenatis dignissim. Cras ut scelerisque ligula. Integer vestibulum pellentesque leo in congue. Nunc volutpat lacus tempus blandit tempus. Sed nec interdum tellus. Ut gravida turpis sed congue facilisis. Maecenas quis tortor sit amet quam ultricies consectetur.

Duis mollis in metus ut tempor. Sed ornare varius dapibus. Mauris et finibus massa, in imperdiet tellus. Nulla elementum leo magna, et viverra risus cursus nec. Proin at dignissim felis, at blandit orci. Etiam blandit luctus dapibus. Aenean suscipit, ante nec convallis tincidunt, tellus lacus luctus nibh, sed sodales sem dui nec nisi. Etiam scelerisque blandit lacinia. Aliquam sit amet purus mauris. Donec pulvinar commodo neque at pretium. Suspendisse pellentesque, dui at auctor porttitor, magna tellus vestibulum libero, nec ultrices mauris est finibus tellus. Sed eu mauris a dolor posuere mattis ac nec orci.

In vel nunc ut felis ultrices iaculis ut non purus. Nulla suscipit at nisl vitae vulputate. Quisque venenatis est quis congue imperdiet. Mauris sodales nulla eu ex interdum rhoncus. Aenean molestie nisi quam, nec tempor neque auctor eget. Aliquam eu purus faucibus, tincidunt odio ac, lobortis sapien. Vestibulum volutpat nulla vel eros ultricies, nec feugiat tellus luctus.

Donec et neque ac urna mattis finibus ac id urna. Aliquam vel ante lacinia, tincidunt neque dapibus, imperdiet erat. Donec tempus varius lorem, et consequat magna tempor ac. Maecenas vitae maximus eros, ut bibendum justo. Aenean aliquam ut tortor non fringilla. Vivamus vel elementum ligula, sed interdum dui. Ut iaculis neque in feugiat venenatis. Sed nisi elit, feugiat eget nulla tristique, scelerisque tempus enim.

Proin mauris lectus, consequat non risus a, rutrum cursus lorem. Pellentesque vel tellus lobortis odio vulputate commodo. Pellentesque et elementum lorem, non rutrum sapien. Fusce id orci quam. Praesent pharetra, ante nec sollicitudin molestie, ligula ex venenatis erat, vitae dictum urna felis vitae lectus. Integer consectetur sed sem at consequat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque lacinia a urna in elementum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

Fusce efficitur lacinia ante. Morbi vel augue non urna scelerisque varius vitae at elit. Maecenas suscipit quam et lacus rutrum volutpat. Nam quis egestas nulla. Curabitur lorem nisi, auctor nec odio eget, commodo pellentesque odio. Praesent pellentesque quam neque, nec rutrum ligula condimentum quis. Nunc vel metus neque. Vivamus malesuada erat interdum, auctor urna a, lobortis tortor. Maecenas convallis lectus at libero aliquet, vel ullamcorper tellus suscipit. Sed rhoncus ornare lorem, vel lobortis tortor dictum sit amet. Nunc dapibus, erat in vehicula ultrices, eros dolor vestibulum nisl, sit amet mollis est nunc ac diam. Nulla quis libero eget enim consectetur commodo consequat eget sem. Cras vel sollicitudin risus. Quisque eget velit gravida, commodo libero vitae, egestas orci. Nunc interdum dictum porttitor.

Mauris a nibh euismod, finibus lectus vitae, bibendum lacus. Nullam hendrerit nunc mi, a semper metus consectetur vitae. Mauris luctus elementum egestas. Etiam mauris sem, dictum pulvinar dolor non tortor.


"""

LOREMIPSUM_PARAGRAPH_DIFF = """Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum bibendum elit id est sodales, eu sollicitudin arcu condimentum. Fusce sodales lacus id leo venenatis, ut finibus velit facilisis. Morbi fringilla, massa eget dictum vulputate, odio lorem mollis ante, ac pretium tellus urna vitae dolor. Etiam porttitor ipsum at sapien lacinia hendrerit. Ut venenatis, eros vel ultricies ultrices, nisi libero viverra enim, gravida rhoncus velit nibh vel ex. Aenean quis odio non eros imperdiet consequat. Aliquam id aliquet libero. Cras eu ex ut lectus tempor facilisis. Pellentesque vel massa posuere, congue leo eu, dapibus orci. Suspendisse in arcu in quam fringilla tempus vel sed nisl.

Cras bibendum nunc metus, vel luctus nisl iaculis eu. Nulla eu fringilla neque. Donec pretium risus lacus, a eleifend leo consectetur id. Nam nec luctus turpis. Nam ultricies quam sed leo dapibus, et aliquet eros lobortis. Nullam metus lacus, posuere quis commodo nec, ultrices a eros. In vel elementum arcu, eu semper nisi. Aenean ac mollis diam. Donec elementum felis a pharetra vehicula. Phasellus sagittis ipsum sed felis accumsan molestie. Praesent urna nibh, maximus et finibus vitae, aliquet sit amet sapien. Nullam sit amet ex accumsan, lobortis arcu vel, finibus magna.

Praesent eget nunc sed sapien mattis ultrices. Aliquam lectus diam, varius quis aliquam eget, efficitur a dui. Nam ac hendrerit libero. Donec pellentesque velit nec lacinia porttitor. Morbi in risus id mi facilisis aliquam. Curabitur elementum nisl convallis, facilisis tortor eu, eleifend eros. Suspendisse cursus justo sed erat pretium consequat. Cras aliquam massa et laoreet scelerisque. Aenean volutpat lacus nec aliquam cursus. Cras pulvinar venenatis neque, sit amet blandit lorem elementum vitae.

Mauris sit amet bibendum enim. Suspendisse dignissim gravida lectus porta malesuada. Duis elementum, nulla id pretium placerat, nunc felis dapibus justo, vitae viverra mauris urna id tortor. Aliquam quis nisi eu velit cursus vestibulum non eu sem. Quisque nec sem auctor, porta justo nec, interdum ipsum. Mauris sollicitudin neque quam, ut pulvinar turpis porttitor a. Donec sit amet nisl id odio tincidunt varius ac a nibh.

Aenean ac tincidunt est. Mauris nunc orci, venenatis eget nibh quis, dictum cursus quam. In at eleifend metus. Maecenas sagittis quis dolor nec tempor. Sed ut nisl risus. Cras ligula nunc, tempor vitae pharetra non, sagittis varius arcu. Nunc semper lorem vitae purus ornare porta.

Maecenas cursus sem vulputate, aliquet nibh nec, pulvinar urna. Nunc at libero porttitor justo ultrices blandit. In pretium, enim quis ultricies cursus, dui ligula luctus dolor, ac elementum ipsum diam ac felis. Vivamus sit amet sem et mauris interdum blandit. Praesent eget tellus ipsum. Sed rhoncus rhoncus leo ut hendrerit. Nunc sed velit libero. Mauris turpis eros, placerat porttitor ligula ac, lacinia sollicitudin est. Quisque aliquet odio pharetra lacus tincidunt, quis tincidunt libero vulputate. Ut imperdiet, risus nec malesuada varius, sem erat semper eros, a maximus purus ex id nisi.

Etiam a nisi risus. Sed nisi justo, euismod quis vulputate sed, bibendum ut eros. Nulla neque ipsum, eleifend at lacus a, convallis molestie augue. Fusce sodales nisl at justo rhoncus, a feugiat nunc bibendum. Fusce eu metus id est fringilla condimentum a ac nibh. Etiam sit amet rutrum tellus, non blandit dolor. Suspendisse eu felis sed nunc egestas molestie. Integer cursus risus sed vulputate auctor. Suspendisse porttitor, ex vel pretium accumsan, magna diam feugiat mauris, ac vulputate lorem ligula at nisl. Aliquam ac venenatis magna. Nullam malesuada nisi et aliquet imperdiet. In interdum posuere massa in lobortis. Cras in eleifend lacus.

Nulla quis luctus tellus, et aliquam turpis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ut suscipit eros, ac ornare ipsum. Duis varius posuere lacus cursus porta. Sed pulvinar, lorem sit amet vulputate venenatis, est elit imperdiet urna, eget consectetur sem quam vel leo. Maecenas eleifend ultrices metus, vel lobortis orci tempor sit amet. Aliquam velit sapien, venenatis in ligula suscipit, mattis finibus est. Vivamus ultrices lorem tortor, ut semper eros feugiat quis. Donec sagittis massa est, eget aliquet tellus varius sit amet. Suspendisse potenti. Donec euismod tellus id vulputate imperdiet. Donec id velit non leo consequat sodales.

Donec ac vulputate magna. Sed eu lacinia dolor. Ut nibh turpis, accumsan vitae aliquam et, aliquam at ante. Curabitur eu ullamcorper enim. Vivamus in sodales justo, nec imperdiet nibh. In mauris lorem, tempor quis orci ultrices, tempor suscipit justo. Nullam lorem tellus, sodales id feugiat in, mattis hendrerit ante. Maecenas nec bibendum dui, a ultrices mauris. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras porttitor, turpis a rhoncus congue, tellus leo maximus sapien, eget fringilla leo nisi ut quam. Morbi quis ipsum ac erat tristique placerat. Cras commodo finibus lorem at porttitor.

Quisque felis elit, eleifend vitae vulputate in, eleifend nec lorem. Fusce varius quis lectus sed congue. Quisque sapien nunc, placerat nec efficitur ac, pharetra eu lorem. Phasellus mattis accumsan ligula nec tincidunt. Duis aliquam commodo quam pretium blandit. Etiam ac scelerisque sem, nec cursus nisl. Quisque dapibus sit amet augue sit amet bibendum. Duis gravida enim sit amet enim tristique varius. Aliquam at sagittis tortor. Quisque finibus augue quis purus rhoncus, a consequat lorem faucibus. Etiam et accumsan diam. Suspendisse venenatis, massa eget fermentum facilisis, urna neque consequat tellus, in egestas est ipsum vitae odio. Nulla pharetra maximus hendrerit. Cras sem odio, scelerisque vitae congue sed, lobortis ut dui. Curabitur nec eleifend sapien.

Sed posuere elit velit, at congue ipsum maximus et. Vivamus ultricies nisl ipsum, vehicula scelerisque turpis ornare id. Aenean sapien orci, accumsan sed risus sodales, tincidunt interdum erat. Sed non viverra dolor, at gravida nisl. Curabitur consectetur odio sed sapien venenatis dignissim. Cras ut scelerisque ligula. Integer vestibulum pellentesque leo in congue. Nunc volutpat lacus tempus blandit tempus. Sed nec interdum tellus. Ut gravida turpis sed congue facilisis. Maecenas quis tortor sit amet quam ultricies consectetur.

Duis mollis in metus ut tempor. Sed ornare varius dapibus. Mauris et finibus massa, in imperdiet tellus. Nulla elementum leo magna, et viverra risus cursus nec. Proin at dignissim felis, at blandit orci. Etiam blandit luctus dapibus. Aenean suscipit, ante nec convallis tincidunt, tellus lacus luctus nibh, sed sodales sem dui nec nisi. Etiam scelerisque blandit lacinia. Aliquam sit amet purus mauris. Donec pulvinar commodo neque at pretium. Suspendisse pellentesque, dui at auctor porttitor, magna tellus vestibulum libero, nec ultrices mauris est finibus tellus. Sed eu mauris a dolor posuere mattis ac nec orci.

In vel nunc ut felis ultrices iaculis ut non purus. Nulla suscipit at nisl vitae vulputate. Quisque venenatis est quis congue imperdiet. Mauris sodales nulla eu ex interdum rhoncus. Aenean molestie nisi quam, nec tempor neque auctor eget. Aliquam eu purus faucibus, tincidunt odio ac, lobortis sapien. Vestibulum volutpat nulla vel eros ultricies, nec feugiat tellus luctus.

Donec et neque ac urna mattis finibus ac id urna. Aliquam vel ante lacinia, tincidunt neque dapibus, imperdiet erat. Donec tempus varius lorem, et consequat magna tempor ac. Maecenas vitae maximus eros, ut bibendum justo. Aenean aliquam ut tortor non fringilla. Vivamus vel elementum ligula, sed interdum dui. Ut iaculis neque in feugiat venenatis. Sed nisi elit, feugiat eget nulla tristique, scelerisque tempus enim.

Proin mauris lectus, consequat non risus a, rutrum cursus lorem. Pellentesque vel tellus lobortis odio vulputate commodo. Pellentesque et elementum lorem, non rutrum sapien. Fusce id orci quam. Praesent pharetra, ante nec sollicitudin molestie, ligula ex venenatis erat, vitae dictum urna felis vitae lectus. Integer consectetur sed sem at consequat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque lacinia a urna in elementum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

Fusce efficitur lacinia ante. Morbi vel augue non urna scelerisque varius vitae at elit. Maecenas suscipit quam et lacus rutrum volutpat. Nam quis egestas nulla. Curabitur lorem nisi, auctor nec odio eget, commodo pellentesque odio. Praesent pellentesque quam neque, nec rutrum ligula condimentum quis. Nunc vel metus neque. Vivamus malesuada erat interdum, auctor urna a, lobortis tortor. Maecenas convallis lectus at libero aliquet, vel ullamcorper tellus suscipit. Sed rhoncus ornare lorem, vel lobortis tortor dictum sit amet. Nunc dapibus, erat in vehicula ultrices, eros dolor vestibulum nisl, sit amet mollis est nunc ac diam. Nulla quis libero eget enim consectetur commodo consequat eget sem. Cras vel sollicitudin risus. Quisque eget velit gravida, commodo libero vitae, egestas orci. Nunc interdum dictum porttitor.

Mauris a nibh euismod, finibus lectus vitae, bibendum lacus. Nullam hendrerit nunc mi, a semper metus consectetur vitae. Mauris luctus elementum egestas. Etiam mauris sem, dictum pulvinar dolor non tortor.


"""

SMALL_TEXT0 = "Small text for tests"

SMALL_TEXT1 = "Small text for tests in files"

SMALL_TEXT2 = "Small text for tests in files other placeholders"
